name: CI-CD # Give your workflow a name

on: push # Run the workflow for each push event (i.e commit)

jobs:
  build-js:
    name: Build Js/Css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        # Build JS
  test-php:
      name: Test/Lint PHP
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        # Test and Lint PHP code
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-js, test-php]
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
 #   - name: Composer install
 #     run: composer install
#    - name: Setup Deployer
#      uses: atymic/deployer-php-action@master
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
#    - name: Deploy to Prod
#    env:
#      DOT_ENV: ${{ secrets.DOT_ENV }}
#      run: dep deploy development
#--tag=${{ env.GITHUB_REF }} -vvv