name: CI-CD # Give your workflow a name

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    #needs: [build-js, test-php]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}	
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        branch: master
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - uses: actions/checkout@v1
#    - name: Download build assets
#      uses: actions/download-artifact@v1
#      with:
#        name: assets
#        path: public
#    - name: Setup PHP
#      uses: dharmendra-sid-jiem/deployer-testing@master
#      with:
#        php-version: 7.3
#        extension-csv: mbstring, bcmath
#    - name: Composer install
#      run: composer install
    - name: Setup Deployer
      uses: atymic/deployer-php-action@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - name: Deploy to Prod
    #env:
      #DOT_ENV: ${{ secrets.DOT_ENV }}
      run: dep deploy development -vvv 
# --tag=${{ env.GITHUB_REF }} -vvv